interface CloudflareEnv {
// Make sure to include it in tsconfig.json
  SYSTEM_PROMPT: string;
  REPLICATE_API_TOKEN: string;
  NEXT_PUBLIC_POSTHOG_KEY: string;
  NEXT_PUBLIC_POSTHOG_HOST: string;
  NEXT_PUBLIC_WORKER_URL?: string; // Worker URL for production/preview (e.g., https://agent-worker-do.workers.dev)
}

/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 0588350abbb82f70ebe13bb57f6b9415)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY?: string;
		AI_GATEWAY_API_KEY: string;
		SANDBOX_API_KEY?: string;
		Chat: DurableObjectNamespace<import("./src/agent-worker/server").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_API_KEY" | "SANDBOX_API_KEY">> {}
}
