/**
 * Types for the Regex Editor Interface
 *
 * This module defines all TypeScript interfaces and types used by the
 * regex editor component for testing and validating regular expressions.
 */

/**
 * Available regex flags for pattern matching.
 * - `g`: Global search (find all matches)
 * - `i`: Case-insensitive search
 * - `m`: Multi-line mode (^ and $ match line boundaries)
 */
export type RegexFlag = "g" | "i" | "m";

/**
 * Supported runtime environments for regex execution.
 * Different runtimes may have subtle differences in regex behavior.
 */
export type Runtime = "javascript" | "typescript" | "python";

/**
 * Available test modes for regex validation.
 * - `match`: Tests whether input strings match or don't match the pattern
 * - `capture`: Tests whether captured groups match expected values
 */
export type TestMode = "match" | "capture";

/**
 * Result for a single test case execution.
 * Contains the input tested and whether it passed, along with
 * mode-specific result data.
 */
export interface TestCaseResult {
  /** The input string that was tested */
  input: string;
  /** Whether this test case passed */
  passed: boolean;
  /** Captured groups (for capture mode) */
  groups?: (string | null)[];
  /** Whether the pattern matched the input (for match mode) */
  matched?: boolean;
}

/**
 * Complete state for the regex editor component.
 * Tracks the current pattern, settings, and test results.
 */
export interface RegexEditorState {
  /** The regex pattern string (without delimiters) */
  pattern: string;
  /** Active regex flags */
  flags: RegexFlag[];
  /** Current test mode (match or capture) */
  mode: TestMode;
  /** Selected runtime for execution */
  runtime: Runtime;
  /** Multi-line test input (each line is a separate test case) */
  testInput: string;
  /** Whether a test is currently running */
  isLoading: boolean;
  /** Error message if the pattern is invalid or test failed */
  error?: string;
  /** Results from the most recent test run */
  results?: TestCaseResult[];
}

/**
 * Props passed to initialize the editor from agent output.
 * Used when the AI agent generates a regex and we need to
 * populate the editor with the result.
 */
export interface RegexEditorInitialData {
  /** The regex pattern generated by the agent */
  pattern: string;
  /** Flags as a string (e.g., "gi") */
  flags: string;
  /** Runtime used for testing (optional) */
  runtime?: string;
  /** Test results from the agent's validation */
  testResults?: {
    /** The test mode used */
    mode?: TestMode;
    /** Detailed results for each test case */
    details?: Array<{
      /** The input that was tested */
      input: string;
      /** Whether the test passed */
      passed: boolean;
      /** Expected value (string for match, array for capture) */
      expected?: string | (string | null)[];
      /** Actual value returned by the regex */
      actual?: string | (string | null)[] | null;
    }>;
  };
}

/**
 * API request shape for the regex test endpoint.
 * Matches the existing backend API contract.
 */
export interface RegexTestRequest {
  /** The regex pattern to test */
  pattern: string;
  /** Regex flags as a string (e.g., "gi") */
  flags?: string;
  /** Test mode to use */
  mode: TestMode;
  /** Runtime environment for execution */
  runtime?: "javascript" | "python";
  /** Inputs that should match the pattern (for match mode) */
  shouldMatch?: string[];
  /** Inputs that should not match the pattern (for match mode) */
  shouldNotMatch?: string[];
  /** Capture group tests (for capture mode) */
  captureTests?: Array<{
    /** Input string to test */
    input: string;
    /** Expected captured groups */
    expectedGroups: (string | null)[];
  }>;
}

/**
 * API response shape from the regex test endpoint.
 * Contains summary statistics and detailed results.
 */
export interface RegexTestResponse {
  /** Whether all tests passed */
  passed: boolean;
  /** Total number of test cases */
  total: number;
  /** Number of passing tests */
  passedCount: number;
  /** Number of failing tests */
  failedCount: number;
  /** Detailed results for each test case */
  results: Array<{
    /** The input that was tested */
    input: string;
    /** Whether this test passed */
    passed: boolean;
    /** Expected value for this test */
    expected?: unknown;
    /** Actual value produced by the regex */
    actual?: unknown;
  }>;
  /** Unique identifier for the sandbox used */
  sandboxId: string;
  /** Runtime that was used for execution */
  runtime: "javascript" | "python";
  /** Test mode that was used */
  testMode: TestMode;
}
